# Generated by Django 5.0.6 on 2024-06-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usersignup_profil_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='apoiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('time', models.DateTimeField()),
                ('pho', models.IntegerField()),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='usersignup',
        ),
    ]
