# Generated by Django 5.0.6 on 2024-06-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_apoiment_delete_usersignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoiment',
            name='pho',
            field=models.CharField(max_length=10),
        ),
    ]
