# Generated by Django 5.0.6 on 2024-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_apoiment_pho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoiment',
            name='time',
            field=models.DateField(),
        ),
    ]
