# Generated by Django 5.0.6 on 2024-06-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_apoiment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoiment',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
